name: 'Cocotb Simulation'
description: 'Runs cocotb for RsDecoder.'
runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash      
      run: |
        ls
        sudo apt-get update
        sudo apt-get install -y libunwind-dev
        sudo apt-get install -y git help2man perl make autoconf g++ flex libfl-dev bison ccache numactl perl-doc

    - name: Install Verilator
      shell: bash
      run: |
        git clone https://github.com/verilator/verilator.git  
        cd verilator  
        git checkout v5.022  
        autoconf  
        ./configure  
        make -j$(nproc)  
        sudo make install
        rm -rf verilator

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python packages
      shell: bash
      run: |
        pip install cocotb==1.8.1
        pip install reedsolo

    - name: run sim
      shell: bash
      working-directory: ./coco_sim
      run: |
        python3 rs_decoder.py -l RsBlockRecovery
