name: CI/CD for Chisel Project

on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: '11'

    - name: Set up sbt
      uses: olafurpg/setup-scala@v13
      with:
        sbt-version: '1.5.5'

    - name: Cache sbt dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
    
    - name: Build Chisel project
      run: sbt compile
      
    - name: Generate Verilog
      run: sbt "runMain Rs.GenRsBlockRecovery"
      
    - name: Upload RsBlockRecovery.sv
      uses: actions/upload-artifact@v4
      with:
        name: RsBlockRecovery.sv
        path: ./RsBlockRecovery.sv

  coco_sim:
    runs-on: ubuntu-latest
    needs: build
    
    steps:

    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: RsBlockRecovery.sv
        path: ./RsBlockRecovery.sv
      run: ls -R
        
    - name: Install Dependencies
      run: |
        ls
        sudo apt-get update
        sudo apt-get install -y libunwind-dev
        sudo apt-get install -y git help2man perl make autoconf g++ flex libfl-dev bison ccache numactl perl-doc

    # Cache the Verilator build directory
    - name: Cache Verilator
      id: verilator-cache
      uses: actions/cache@v2
      with:
        path: |      
          /usr/local/share/verilator
          /usr/local/bin/verilator
        key: verilator-${{ runner.os }}-v5.022
        restore-keys: |        
          verilator-${{ runner.os }}-
        
    - name: Install Verilator
      if: steps.verilator-cache.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/verilator/verilator.git  
        cd verilator  
        git checkout v5.022  
        autoconf  
        ./configure  
        make -j$(nproc)  
        sudo make install
        rm -rf verilator

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python packages
      run: |
        pip install cocotb==1.8.1
        pip install reedsolo

    - name: run sim
      working-directory: ./coco_sim
      run: |
        python3 rs_decoder.py -l RsBlockRecovery
