name: CI/CD for Chisel Project

on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main

jobs:
  dec_p285_n255_k239:    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bus-width: [4, 8]
        
    steps:
    - name: build
      uses: ./.github/actions/chisel-build
      with:
        axis_clock: '100.0'
        core_clock: '200.0'
        symb_width: '8'
        bus_width: '32'
        poly: '285'
        n_len: '255'
        k_len: '239'

    - name: coco-sim
      uses: ./.github/actions/cocotb-sim
